# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/persistent_state.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from proto import log_entry_pb2 as proto_dot_log__entry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/persistent_state.proto',
  package='persistent_state',
  syntax='proto3',
  serialized_pb=_b('\n\x1cproto/persistent_state.proto\x12\x10persistent_state\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x15proto/log_entry.proto\"\x82\x01\n\x0fPersistentState\x12\x14\n\x0c\x63urrent_term\x18\x01 \x01(\r\x12/\n\tvoted_for\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\x12(\n\x0blog_entries\x18\x03 \x03(\x0b\x32\x13.log_entry.LogEntryb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,proto_dot_log__entry__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PERSISTENTSTATE = _descriptor.Descriptor(
  name='PersistentState',
  full_name='persistent_state.PersistentState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_term', full_name='persistent_state.PersistentState.current_term', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voted_for', full_name='persistent_state.PersistentState.voted_for', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='log_entries', full_name='persistent_state.PersistentState.log_entries', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=236,
)

_PERSISTENTSTATE.fields_by_name['voted_for'].message_type = google_dot_protobuf_dot_wrappers__pb2._UINT32VALUE
_PERSISTENTSTATE.fields_by_name['log_entries'].message_type = proto_dot_log__entry__pb2._LOGENTRY
DESCRIPTOR.message_types_by_name['PersistentState'] = _PERSISTENTSTATE

PersistentState = _reflection.GeneratedProtocolMessageType('PersistentState', (_message.Message,), dict(
  DESCRIPTOR = _PERSISTENTSTATE,
  __module__ = 'proto.persistent_state_pb2'
  # @@protoc_insertion_point(class_scope:persistent_state.PersistentState)
  ))
_sym_db.RegisterMessage(PersistentState)


# @@protoc_insertion_point(module_scope)
